CREATE DATABASE pasmine_pasa;
USE pasmine_pasa;
CREATE TABLE pasmina
(id INT auto_increment PRIMARY key,
naziv_pasmina varchar(100),
zemlja_podrijetla VARCHAR(100));

INSERT INTO pasmina (naziv_pasmina, zemlja_podrijetla) VALUES
('Affenpinscher', 'Germany'),
('Afghan Hound', 'Afghanistan'),
('Airedale Terrier', 'Great Britain'),
('Akita', 'Japan'),
('Alaskan Klee Kai', 'Alaska'),
('Alaskan Malamute', 'Alaska'),
('American Bulldog', 'United States'),
('American English Coonhound', 'United States'),
('American Eskimo Dog', 'United States'),
('American Foxhound', 'United States'),
('American Hairless Terrier', 'United States'),
('American Leopard Hound', 'United States'),
('American Staffordshire Terrier', 'United States'),
('American Water Spaniel', 'United States'),
('Anatolian Shepherd Dog', 'Turkey'),
('Appenzeller Sennenhund', 'Switzerland'),
('Australian Cattle Dog', 'Australia'),
('Australian Kelpie', 'Australia'),
('Australian Shepherd', 'Australia'),
('Australian Stumpy Tail Cattle Dog', 'Australia'),
('Australian Terrier', 'Australia'),
('Azawakh', 'Mali'),
('Barbado da Terceira', 'Portugal'),
('Barbet', 'France'),
('Basenji', 'Democratic Republic of the Congo'),
('Basset Fauve de Bretagne', 'France'),
('Basset Hound', 'France'),
('Bavarian Mountain Scent Hound', 'Germany'),
('Beagle', 'Great Britain'),
('Bearded Collie', 'Scotland'),
('Beauceron', 'France'),
('Bedlington Terrier', 'Great Britain'),
('Belgian Laekenois', 'Belgium'),
('Belgian Malinois', 'Belgium'),
('Belgian Sheepdog', 'Belgium'),
('Belgian Tervuren', 'Belgium'),
('Bergamasco Sheepdog', 'Italy'),
('Berger Picard', 'France'),
('Bernese Mountain Dog', 'Switzerland'),
('Bichon Frise', 'France'),
('Biewer Terrier', 'Germany'),
('Black and Tan Coonhound', 'United States'),
('Black Russian Terrier', 'Russia'),
('Bloodhound', 'Belgium'),
('Blue Picardy Spaniel', 'France'),
('Bluetick Coonhound', 'United States'),
('Boerboel', 'South Africa'),
('Bohemian Shepherd', 'Czech Republic'),
('Bolognese', 'Italy'),
('Border Collie' , 'Great Britain'),
('Border Terrier', 'Great Britain'),
('Borzoi', 'Russia'),
('Boston Terrier', 'United States'),
('Bouvier des Ardennes', 'Belgium'),
('Bouvier des Flandres', 'Belgium'),
('Boxer', 'Germany'),
('Boykin Spaniel', 'United States'),
('Bracco Italiano', 'Italy'),
('Braque du Bourbonnais', 'France'),
('Braque Francais Pyrenean', 'France'),
('Braque Saint-Germain', 'France'),
('Brazilian Terrier', 'Brazil'),
('Briard', 'France'),
('Brittany', 'France'),
('Broholmer', 'Denmark'),
('Brussels Griffon', 'Belgium'),
('Bull Terrier', 'Great Britain'),
('Bulldog', 'Great Britain'),
('Bullmastiff', 'Great Britain');
